function bindEvents() {
  dom.instrumentSwitch.addEventListener('click', (event) => { const button = event.target.closest('button[data-instrument]'); if (button) setInstrument(button.dataset.instrument); });
  dom.tuningButton.addEventListener('click', openTuningDialog); dom.newCustomTuningButton.addEventListener('click', () => openCustomTuningEditor()); dom.customTuningForm.addEventListener('submit', saveCustomTuning); dom.settingsButton.addEventListener('click', () => { renderSettings(); dom.settingsDialog.showModal(); }); dom.microphoneButton.addEventListener('click', toggleMicrophone); dom.toneButton.addEventListener('click', toggleReferenceTone); dom.modeButton.addEventListener('click', () => setMode(settings.mode === 'auto' ? 'manual' : 'auto')); dom.resetProgressButton.addEventListener('click', resetProgress);
  document.querySelectorAll('.close-dialog').forEach((button) => button.addEventListener('click', () => button.closest('dialog')?.close())); document.querySelectorAll('dialog').forEach((dialog) => dialog.addEventListener('click', (event) => { if (event.target === dialog) dialog.close(); }));
  dom.referencePitch.addEventListener('input', () => setReferencePitch(dom.referencePitch.value)); dom.referenceDown.addEventListener('click', () => setReferencePitch(settings.referenceA - 1)); dom.referenceUp.addEventListener('click', () => setReferencePitch(settings.referenceA + 1));
  dom.sensitivity.addEventListener('input', () => { settings.sensitivity = Number(dom.sensitivity.value); dom.sensitivityValue.textContent = sensitivityLabel(settings.sensitivity); saveSettings(); });
  dom.accidentalSwitch.addEventListener('click', (event) => { const button = event.target.closest('button[data-value]'); if (!button) return; settings.accidentalMode = button.dataset.value; renderSettings(); updateCurrentTuning({ resetProgress: false }); });
  dom.themeSwitch.addEventListener('click', (event) => { const button = event.target.closest('button[data-value]'); if (!button) return; settings.theme = button.dataset.value; applyTheme(); saveSettings(); });
  dom.vibrationToggle.addEventListener('change', () => { settings.vibration = dom.vibrationToggle.checked; saveSettings(); });
  dom.wakeLockToggle.addEventListener('change', async () => { settings.wakeLock = dom.wakeLockToggle.checked; saveSettings(); if (settings.wakeLock) await requestWakeLock(); else await releaseWakeLock(); });
  dom.resetSettingsButton.addEventListener('click', resetPreferences); dom.installAppButton.addEventListener('click', async () => { if (!deferredInstallPrompt) return; deferredInstallPrompt.prompt(); await deferredInstallPrompt.userChoice; deferredInstallPrompt = null; dom.installAppButton.hidden = true; });
  window.addEventListener('beforeinstallprompt', (event) => { event.preventDefault(); deferredInstallPrompt = event; dom.installAppButton.hidden = false; }); window.addEventListener('appinstalled', () => { deferredInstallPrompt = null; dom.installAppButton.hidden = true; showToast('Fretline installed'); });
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => { if (settings.theme === 'system') applyTheme(); }); document.addEventListener('visibilitychange', async () => { if (document.visibilityState === 'visible') await requestWakeLock(); else await releaseWakeLock(); }); window.addEventListener('pagehide', () => mediaStream?.getTracks().forEach((track) => track.stop()));
  document.addEventListener('keydown', (event) => { const activeTag = document.activeElement?.tagName; const dialogOpen = Boolean(document.querySelector('dialog[open]')); if (event.code === 'Space' && !dialogOpen && !['INPUT', 'SELECT', 'TEXTAREA', 'BUTTON'].includes(activeTag)) { event.preventDefault(); toggleMicrophone(); } });
}
function registerServiceWorker() { if (!('serviceWorker' in navigator) || !window.isSecureContext) return; window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js').catch(() => {})); }
function initialize() {
  initializeMeterTicks(); applyTheme(); renderSettings(); updateCurrentTuning(); bindEvents(); registerServiceWorker();
  if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) { dom.tunerCard.dataset.state = 'error'; dom.listenStatus.textContent = 'Microphone unavailable'; dom.pitchInstruction.textContent = !window.isSecureContext ? 'Open this tuner over HTTPS to use the microphone.' : 'This browser does not support microphone input.'; }
}
initialize();
